config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'home/index'  
  resources :user_rooms, only: [:update, :show, :destroy]
  post 'user_rooms/:id', to: 'user_rooms#create'
  resources :rooms do
    resources :teams
    resources :pickups
    resources :students do
      resources :comments, only: [:create]
    end

    put 'students/:id/update', to: 'students#update_edit'
    put 'students/ride/reset', to: 'students#reset_ride'
    put 'students/attend/reset', to:'students#reset_attend'
  end
end

app/models/student.rb
class Student < ApplicationRecord
  validates :last_name, presence: true
  validates :first_name, presence: true

  belongs_to :room, foreign_key: 'room_id'
  belongs_to :team, optional: true
  belongs_to :pickup, optional: true
  belongs_to :ride, optional: true
  belongs_to :attend, optional: true
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_root
  before_action :set_room
  before_action :set_student, only: [:edit, :update, :show, :destroy, :update_edit]

  def index
    @students = Student.where(room_id: @room.id).where(team_id: nil).order(last_name: :asc).order(first_name: :asc)
    @pickups = Pickup.where(room_id: @room.id)
    @teams = Team.where(room_id: @room.id)
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(params_student)
    if @student.save
      redirect_to room_students_path
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    @comments = @student.comments.includes(:student).order(created_at: :desc)
  end

  def edit
  end

  def update
    @student.update_attributes(params_ride_attend)
  end

  def update_edit
    if @student.update_attributes(params_student)
      redirect_to room_student_path
    else
      render 'edit'
    end
  end

  def destroy
    if @student.destroy
      redirect_to room_students_path
    else
      render 'edit'
    end
  end

  def reset_attend
    @students = Student.all
    @students.each do |s|
      s.attend_id = nil
      s.save
    end
    redirect_to room_students_path(id: params[:room_id])
  end

  def reset_ride
    @students = Student.all
    @students.each do |s|
      s.ride_id = nil
      s.save
    end
    redirect_to room_students_path(id: params[:room_id])
  end

  private

  def move_to_root
    @user_rooms = UserRoom.where(room_id: params[:room_id])
    return if @user_rooms.exists?(user_id: current_user.id)

    redirect_to root_path
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def params_student
    params.require(:student)
          .permit(:last_name, :first_name, :team_id, :pickup_id, :image)
          .merge(room_id: params[:room_id])
  end

  def params_ride_attend
    params.require(:student)
          .permit(:ride_id, :attend_id)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<%= render partial:'shared/third_header' %>
<div class="main-page">
  <div class="form">
    <div class="form-title">
      <h2>児童内容編集</h2>
    </div>
    <%= form_with model:[@room,@student], url: "/rooms/#{params[:room_id]}/students/#{params[:id]}/update", method: :PUT, local: true do |f| %>
      <div class="form-errors">
        <% if @student.errors.any? %>
        <div class="error-alert">
          <ul>
            <% @student.errors.full_messages.each do |message| %>
            <li class='error-message'><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>  
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :image,"画像" %>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :last_name,"苗字" %>
        </div>
        <div class="form-field">
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
        </div>
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :first_name,"名前" %>
        </div>
        <div class="form-field">
          <%= f.text_field :first_name, autocomplete: "first_name" %>
        </div>
      </div>
      <div class="field">
        <div class="form-label">
          <%= f.label :team_id,"クラス" %>
        </div>
        <div class="form-field">
          <%= f.collection_select(:team_id, Team.where(room_id: @room.id), :id, :name, {include_blank: true}, {class:"select-box", id:"team-category"}) %>
        </div>
      </div>
      <div class="field">
        <div class="form-label">
          <%= f.label :pickup_id,"送迎" %>
          </div>
          <div class="form-field">
          <%= f.collection_select(:pickup_id, Pickup.where(room_id: @room.id), :id, :name, {include_blank: true}, {class:"select-box", id:"pickup-category"}) %>
          </div>
        </div>
      </div>
      <div class="actions">
        <span>
          <%= f.submit "編集" %>
        </span>
        <span class="destroy">
          <%= link_to "削除", room_student_path, method: :DELETE, class: "destroy-button"%>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/students/index.html.erb
<%= render partial:'shared/second_header' %>
<div class="main-page">
  <div class="group-index">
    <div class="sidebar">
      <div id="sidebar-top">
        <p><%= @room.name %></p>
        <%= link_to "編集",  edit_room_path(id: params[:room_id]), class:"edit"%>
      </div>
      <div class="sidebar-index">
      <%# クラス、送迎一覧表示 %>
        <ul id="sidebar-lists">
          <li class="sidebar-list-name">クラス</li>
          <%  @teams.each do |t|%>
            <li class="sidebar-list">
              <%=  link_to t.name, room_team_path(id: t.id)%> 
            </li>
          <% end  %>
          <li>送迎</li>
          <% @pickups.each do |i| %>
            <li class="sidebar-list">
              <%=  link_to i.name, room_pickup_path(id: i.id)%> 
            </li>
          <% end %>
        </ul>
      <%# クラス、送迎一覧表示 %>
      </div>
    </div>
    <div class="main">
      <div id="main-top">
      <%# クラス・送迎名 %>
        <p>クラス登録なし</p>
      <%# 編集ボタン %>
        <%# <a href="#">編集</a> %>
      </div>
      <%# 児童一覧表示 %>
      <div id="main-index">
        <ul id="main-lists">
          <% @students.each do |s| %>
            <li class="main-list">
            <%= link_to (room_student_path(id: s.id)) do %>
              <div class="students-name">
                <p class="student-last-name"><%= s.last_name %></p>
                <p class="student-first-name"><%= s.first_name %></p>
              </div>
            <% end %>
            </li>
          <% end %>
        </ul>
        <%# 児童一覧表示 %>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<%= render partial:'shared/third_header' %>
<div class="main-page">
  <div class="form">
    <div class="form-title">
      <h2>児童登録</h2>
    </div>
    <%= form_with model: [@room,@student], local: true do |f| %>
      <div class="form-errors">
      <%= render 'shared/error_messages', model: f.object %>
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :image,"画像" %>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :last_name,"苗字" %>
        </div>
        <div class="form-field">
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
        </div>
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :first_name,"名前" %>
        </div>
        <div class="form-field">
          <%= f.text_field :first_name, autocomplete: "first_name" %>
        </div>
      </div>
      <div class="field">
        <div class="form-label">
          <%= f.label :team_id,"クラス" %>
        </div>
        <div class="form-field">
          <%= f.collection_select(:team_id, Team.where(room_id: @room.id), :id, :name, {include_blank: true}, {class:"select-box", id:"team-category"}) %>
        </div>
      </div>
      <div class="field">
        <div class="form-label">
          <%= f.label :pickup_id,"送迎" %>
          </div>
          <div class="form-field">
          <%= f.collection_select(:pickup_id, Pickup.where(room_id: @room.id), :id, :name, {include_blank: true}, {class:"select-box", id:"pickup-category"}) %>
          </div>
        </div>
      </div>
      <div class="actions">
        <span>
        <%= f.submit "登録する" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<%= render partial:'shared/third_header' %>
<div class="main-page">
  <div class="show-page">
  <%# 画面左 %>
    <div class="student-show-main">
      <div class="student-show">
        <div class="student-name">
          <%= @student.last_name %>
          <%= @student.first_name %>
        </div>
        <div class="student">
          <% if @student.image.attachment != nil %>
            <%= image_tag @student.image, class: "image"%>
          <% else %>
            <%= image_tag "noimage.png" ,class: "image"%>
          <% end %>
        </div>
        <ul class="student-items">
          クラス
          <li class="student-item">
            <% if @student.team != nil %>
              <p><%= @student.team.name %></p>
            <% else %>
              <p>クラスに所属していません。</p>
            <% end %>
          </li>
          送迎
          <li class="student-item">
            <% if @student.pickup != nil %>
              <%= @student.pickup.name %>
            <% else %>
              送迎ではありません
            <% end %>
          </li>
        </ul>
          <div class="actions">
            <span>
            <%= link_to "編集へ", edit_room_student_path %>
            </span>
          </div>
      </div>
      <%# 画面右 %>
      <div class="student-comments">
      <%# コメント投稿フォーム %>
            <%= form_with model: [@room, @student, @comment],local: true do |f|%>
              <div class="field">
                <div class="form-label">
                <%= f.label :content, "コメント" %>
                </div>
                <div class="form-field">
                <%= f.text_field :content %>
                </div>
              </div>
              <div class="actions">
                <span>
                  <%= f.submit "送信する", class: :form__btn  %>
                </span>
              </div>
            <% end %>
      
      <%# コメント表示 %>
        <ul class="comments-lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% @comments.each do |comment|%>
            <li class="comments-list">
              <div class="comment">
                <p class="comment-content">
                  <%= comment.content%>
                </p>
                <p class="comment-user">
                  <%= comment.created_at.to_s(:datetime_jp) %>
                  <%= comment.user.name %>
                </p>
              </div>
            </li>
          <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>

      </div>
    </div>
  </div>
</div>