config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'home/index'  
  resources :user_rooms, only: [:update, :show, :destroy]
  post 'user_rooms/:id', to: 'user_rooms#create'
  resources :rooms do
    resources :teams
    resources :pickups
    resources :students do
      resources :comments, only: [:create]
    end

    put 'students/:id/update', to: 'students#update_edit'
    put 'students/ride/reset', to: 'students#reset_ride'
    put 'students/attend/reset', to:'students#reset_attend'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attend.rb
class Attend < ActiveHash::Base
  self.data = [
    { id: 1, data: 'attendance' },
    { id: 2, data: 'absence' }
  ]
  include ActiveHash::Associations
  has_many :students
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :student
end

app/models/pickup.rb
class Pickup < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }

  belongs_to :room, foreign_key: 'room_id'
  has_many :students
end

app/models/ride.rb
class Ride < ActiveHash::Base
  self.data = [
    { id: 1, data: 'rideOn' },
    { id: 2, data: 'rideOff' }
  ]
  include ActiveHash::Associations
  has_many :students
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }

  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
  has_one :team, dependent: :destroy
  has_one :pickup, dependent: :destroy
  has_one :student, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
  validates :last_name, presence: true
  validates :first_name, presence: true

  belongs_to :room, foreign_key: 'room_id'
  belongs_to :team, optional: true
  belongs_to :pickup, optional: true
  belongs_to :ride, optional: true
  belongs_to :attend, optional: true
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }

  belongs_to :room, foreign_key: 'room_id'
  has_many :students
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:uid]
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers'
  validates :name, presence: true
  validates :uid, presence: true,
                  uniqueness: { case_sensitive: true },
                  length: { minimum: 8, maximum: 16 },
                  format: { with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers' }

  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(['uid = :value', { value: uid }]).first
    else
      where(conditions).first
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_room
  before_action :set_student
  before_action :authenticate_user!
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to  room_student_path(id: params[:student_id])
    else
      @student = @comment.student
      @comments = @student.comments
      redirect_to  room_student_path(id: params[:student_id])
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content).merge(user_id: current_user.id, student_id: params[:student_id])
    end

    def set_room
      @room = Room.find(params[:room_id])
    end
  
    def set_student
      @student = Student.find(params[:student_id])
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_root
  before_action :set_room
  before_action :set_pickup, only: [:edit, :update, :show, :destroy]

  def new
    @pickup = Pickup.new
  end

  def create
    @pickup = Pickup.new(params_pickup)
    if @pickup.save
      redirect_to room_students_path
    else
      render 'new'
    end
  end

  def show
    @students = Student.where(room_id: @room.id).where(pickup_id: @pickup.id).order(last_name: :asc).order(first_name: :asc)
    @pickups = Pickup.where(room_id: @room.id)
    @teams = Team.where(room_id: @room.id)
  end

  def edit
  end

  def update
    if @pickup.update_attributes(params_pickup)
      redirect_to room_pickup_path
    else
      render 'edit'
    end
  end

  def destroy
    if @pickup.destroy
      redirect_to room_students_path(id: params[:room_id])
    else
      redirect_to 'edit'
    end
  end

  private

  def move_to_root
    @user_rooms = UserRoom.where(room_id: params[:room_id])
    return if @user_rooms.exists?(user_id: current_user.id)

    redirect_to root_path
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def params_pickup
    params.require(:pickup).permit(:name).merge(room_id: params[:room_id])
  end

  def set_pickup
    @pickup = Pickup.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_root, except: [:index, :new, :create]
  before_action :set_room, only: [:edit, :update, :show, :destroy]
  def index
    @user_rooms = UserRoom.where(user_id: current_user.id)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params_room)
    if @room.save
      UserRoom.create(room_id: @room.id, user_id: current_user.id)
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  def show
    @user_rooms = UserRoom.where(user_id: current_user.id)
  end

  def edit
    @user_rooms = UserRoom.where(room_id: params[:id])
  end

  def update
    if @room.update_attributes(params_room)
      redirect_to room_path
    else
      render 'edit'
    end
  end

  def destroy
    return unless @room.destroy

    redirect_to rooms_path
  end

  private

  def move_to_root
    @user_rooms = UserRoom.where(room_id: params[:id])
    return if @user_rooms.exists?(user_id: current_user.id)

    redirect_to root_path
  end

  def params_room
    params.require(:room).permit(:name)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_root
  before_action :set_room
  before_action :set_team, only: [:edit, :update, :show, :destroy]

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params_team)
    if @team.save
      redirect_to room_students_path
    else
      render 'new'
    end
  end

  def show
    @students = Student.where(room_id: @room.id).where(team_id: @team.id).order(last_name: :asc).order(first_name: :asc)
    @pickups = Pickup.where(room_id: @room.id)
    @teams = Team.where(room_id: @room.id)
  end

  def edit
  end

  def update
    if @team.update_attributes(params_team)
      redirect_to room_students_path
    else
      render 'edit'
    end
  end

  def destroy
    if @team.destroy
      redirect_to room_students_path(room_id: params[:room_id])
    else
      redirect_to 'edit'
    end
  end

  private

  def move_to_root
    @user_rooms = UserRoom.where(room_id: params[:room_id])
    return if @user_rooms.exists?(user_id: current_user.id)

    redirect_to root_path
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def params_team
    params.require(:team).permit(:name).merge(room_id: params[:room_id])
  end

  def set_team
    @team = Team.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_rooms_helper.rb
module UserRoomsHelper
end

app/views/pickups/edit.html.erb
<%= render partial:'shared/third_header' %>
<div class="main-page">
  <div class="form">
    <div class="form-title">
      <h2>送迎編集</h2>
    </div>
    <%= form_with model: [@room,@pickup], local: true do |f| %>
      <div class="form-errors">
      <%= render 'shared/error_messages', model: f.object %>
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :name,"送迎名" %>
        </div>
        <div class="form-field">
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>
      </div>

      <div class="actions">
        <span>
        <%= f.submit "変更" %>
        </span>
        <span class="destroy">
        <%= link_to "削除", room_pickup_path, method: :DELETE, class: "destroy-button"%>
        </span>
      </div>
    <% end %>

  </div>
</div>

app/views/pickups/new.html.erb
<%= render partial:'shared/third_header' %>
<div class="main-page">
  <div class="form">
    <div class="form-title">
      <h2>送迎種類新規作成</h2>
    </div>
    <%= form_with model: [@room,@pickup], local: true do |f| %>
      <div class="form-errors">
      <%= render 'shared/error_messages', model: f.object %>
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :name,"送迎名" %>
        </div>
        <div class="form-field">
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>
      </div>

      <div class="actions">
        <span>
        <%= f.submit "作成する" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/pickups/show.html.erb
<%= render partial:'shared/second_header' %>
<div class="main-page">
  <div class="group-index">
    <div class="sidebar">
      <div id="sidebar-top">
        <p><%= @room.name %></p>
        <%= link_to "編集",  edit_room_path(id: params[:room_id]), class:"edit"%>
      </div>
      <div class="sidebar-index">
      <%# クラス、送迎一覧表示 %>
        <ul id="sidebar-lists">
          <li class="sidebar-list-name">クラス</li>
          <%  @teams.each do |t|%>
            <li class="sidebar-list">
              <%=  link_to t.name, room_team_path(id: t.id)%> 
            </li>
          <% end  %>
          <li class="sidebar-list-name">送迎</li>
          <% @pickups.each do |i| %>
            <li class="sidebar-list">
              <%=  link_to i.name, room_pickup_path(id: i.id)%> 
            </li>
          <% end %>
        </ul>
      <%# クラス、送迎一覧表示 %>
      </div>
    </div>
    <div class="main">
      <div id="main-top">
      <%# クラス・送迎名 %>
        <p><%= @pickup.name %></p>
      <%# 編集ボタン %>
        <%= link_to "編集",  edit_room_pickup_path, class:"edit"%>
      </div>
      <%# 児童一覧表示 %>
      <div id="main-index">
        <ul id="main-lists">
          <% @students.each do |s| %>
            <li class="main-list">
            <%# 名前をクリックすると詳細画面に遷移する %>
            <%= link_to (room_student_path(id: s.id)) do %>
              <div class="students-name">
                <p class="student-last-name"><%= s.last_name %></p>
                <p class="student-first-name"><%= s.first_name %></p>
              </div>
            <% end %>
            <%# ボタンクリックで色変更、Studentモデルのride_id,attend_id更新、jsによるAjax動作 %>
              <ul id="index-button-lists">
                <li class="index-button-list">
                  <%= form_with model: [@room,s],method: :PUT, class: "form-ride-on", local: true do |f| %>
                    <% if s.attend_id == 2 %>
                      <%= f.collection_select(:ride_id, Ride.all, :id, :data, {selected: 1},{class: "ride-on-id none"}) %>
                      <%= f.submit("乗車", class: "index-button ride-on", style:"background-color: #CCCCCC;",disabled: true)%>                    
                    <% elsif s.ride_id == 1 %>
                      <%= f.collection_select(:ride_id, Ride.all, :id, :data, {selected: 1},{class: "ride-on-id none"}) %>
                      <%= f.submit("乗車", class: "index-button ride-on", style:"background-color: #FF3366;",disabled: true)%>
                    <% else %>
                      <%= f.collection_select(:ride_id, Ride.all, :id, :data, {selected: 1},{class: "ride-on-id none"}) %>
                      <%= f.submit("乗車", class: "index-button ride-on")%>
                    <% end %>
                  <% end %>
                  <%# <input type="submit" class="index-button ride-on" value="乗車"> %>
                </li>
                <li class="index-button-list">
                  <%= form_with model: [@room,s],method: :PUT, class: "form-ride-off", local: true do |f| %>
                    <% if s.attend_id == 2 %>
                      <%= f.collection_select(:ride_id, Ride.all, :id, :data, {selected: 2},{class: "none"}) %>
                      <%= f.submit("降車", class: "index-button ride-off", style:"background-color: #CCCCCC;",disabled: true)%>                    
                    <% elsif s.ride_id == 2 %>
                      <%= f.collection_select(:ride_id, Ride.all, :id, :data, {selected: 2},{class: "none"}) %>
                      <%= f.submit("降車", class: "index-button ride-off", style:"background-color: #33CCFF;",disabled: true)%>
                    <% else %>
                      <%= f.collection_select(:ride_id, Ride.all, :id, :data, {selected: 2},{class: "none"}) %>
                      <%= f.submit("降車", class: "index-button ride-off")%>
                    <% end %>
                  <% end %>
                  <%# <input type="submit" class="index-button ride-off" value="降車"> %>
                </li>
                <li class="index-button-list">
                  <%= form_with model: [@room,s],method: :PUT, class: "form-attendance", local: true do |f| %>
                    <% if s.attend_id == 1 %>
                      <%= f.collection_select(:attend_id, Attend.all, :id, :data, {selected: 1},{class: "none"}) %>
                      <%= f.submit("出席", class: "index-button attendance", style:"background-color: #66FF66;",disabled: true)%>
                    <% else %>
                      <%= f.collection_select(:attend_id, Attend.all, :id, :data, {selected: 1},{class: "none"}) %>
                      <%= f.submit("出席", class: "index-button attendance")%>
                    <% end %>
                  <% end %>
                  <%# <input type="submit" class="index-button attendance" value="出席"> %>
                </li>
                <li class="index-button-list">
                  <%= form_with model: [@room,s],method: :PUT, class: "form-absence", local: true do |f| %>
                    <% if s.attend_id == 2 %>
                      <%= f.collection_select(:attend_id, Attend.all, :id, :data, {selected: 2},{class: "none"}) %>
                      <%= f.submit("欠席", class: "index-button absence", style:"background-color: #CCCCCC;",disabled: true)%>
                    <% else %>
                      <%= f.collection_select(:attend_id, Attend.all, :id, :data, {selected: 2},{class: "none"}) %>
                      <%= f.submit("欠席", class: "index-button absence")%>
                    <% end %>
                  <% end %>                
                  <%# <input type="submit" class="index-button absence" value="欠席"> %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
      <%# 児童一覧表示 %>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<%= render partial:'shared/header' %>
<div class="main-page">
  <div class="form">
    <div class="form-title">
      <h2>グループ編集</h2>
    </div>
    <div class="group-user">グループ参加ユーザー名</div>
    <ul class="user-lists">
      <% @user_rooms.each do |user_room|%>
        <li class="user-list"><%= user_room.user.name %></li>
      <% end %>
    </ul>
    <%= form_with model: @room, local: true do |f| %>
      <div class="form-errors">
      <%= render 'shared/error_messages', model: f.object %>
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :name,"グループ名" %>
        </div>
        <div class="form-field">
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>
      </div>

      <div class="actions">
        <span>
        <%= f.submit "変更" %>
        </span>
        <span class="destroy">
          <%= link_to "削除", room_path, method: :DELETE, class: "destroy-button"%>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<%= render partial:'shared/header' %>
<div class="main-page">
  <div class="group-index">
    <div class="sidebar">
      <div id="sidebar-top">
        <p>グループ一覧</p>
      </div>
      <div class="sidebar-index">
        <ul id="sidebar-lists">

        <%# パラメーターのルーム内で作成したクラスと送迎種類を表示させる 
        リンク先はteamとpickupのshow%>
        <% @user_rooms.each do |r| %>
          <li class="sidebar-list">
          <%= link_to r.room.name, room_path(id:r.room.id), class:"room-link" %>
          </li>
        <% end %>
        
        </ul>
      </div>
    </div>
    <div class="main">
      <div id="main-top">
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render partial:'shared/header' %>
<div class="main-page">
  <div class="form">
    <div class="form-title">
      <h2>グループ新規作成</h2>
    </div>
    <%= form_with model: @room, local: true do |f| %>
      <div class="form-errors">
      <%= render 'shared/error_messages', model: f.object %>
      </div>
      <div class="field">
        <div class="form-label">
        <%= f.label :name,"グループ名" %>
        </div>
        <div class="form-field">
          <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>
      </div>

      <div class="actions">
        <span>
        <%= f.submit "作成する" %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<%= render partial:'shared/header' %>
<div class="main-page">
  <div class="group-index">
    <div class="sidebar">
      <div id="sidebar-top">
        <p><%= @room.name %></p>
        <%= link_to "編集",  edit_room_path, class:"edit"%>
      </div>
      <div class="sidebar-index">
        <ul id="sidebar-lists">
        <% @user_rooms.each do |r| %>
          <li class="sidebar-list">
          <%= link_to r.room.name, room_path(id:r.room.id), class:"room-link" %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
    <div class="main">
      <div id="main-top">
      <%# 選択されたクラス、送迎名を表示する %>
        <p>各種機能</p>
      <%# 選択されたクラス、送迎の編集ページへリンクする %>
        <%# <a href="#"></a> %>
      </div>
      <div id="main-index">
        <ul id="main-lists">
          <li class="main-list">
            <%= link_to "・児童一覧へ", room_students_path(room_id: params[:id]) %>
          </li>
          <li class="main-list">
            <%= link_to "・児童登録へ", new_room_student_path(room_id: params[:id]) %>
          </li>
          <li class="main-list">
            <%= link_to "・クラス作成へ", new_room_team_path(room_id: params[:id]) %>
          </li>
          <li class="main-list">
            <%= link_to "・送迎種類作成へ",   new_room_pickup_path(room_id: params[:id]) %>
          </li>
          <li class="main-list">
            <%= link_to "・グループユーザー編集へ",   user_room_path(id: params[:id]) %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>