config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'home/index'  
  resources :user_rooms, only: [:update, :show, :destroy]
  post 'user_rooms/:id', to: 'user_rooms#create'
  resources :rooms do
    resources :teams
    resources :pickups
    resources :students do
      resources :comments, only: [:create]
    end

    put 'students/:id/update', to: 'students#update_edit'
    put 'students/ride/reset', to: 'students#reset_ride'
    put 'students/attend/reset', to:'students#reset_attend'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attend.rb
class Attend < ActiveHash::Base
  self.data = [
    { id: 1, data: 'attendance' },
    { id: 2, data: 'absence' }
  ]
  include ActiveHash::Associations
  has_many :students
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :student
end

app/models/pickup.rb
class Pickup < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }

  belongs_to :room, foreign_key: 'room_id'
  has_many :students
end

app/models/ride.rb
class Ride < ActiveHash::Base
  self.data = [
    { id: 1, data: 'rideOn' },
    { id: 2, data: 'rideOff' }
  ]
  include ActiveHash::Associations
  has_many :students
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }

  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
  has_one :team, dependent: :destroy
  has_one :pickup, dependent: :destroy
  has_one :student, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
  validates :last_name, presence: true
  validates :first_name, presence: true

  belongs_to :room, foreign_key: 'room_id'
  belongs_to :team, optional: true
  belongs_to :pickup, optional: true
  belongs_to :ride, optional: true
  belongs_to :attend, optional: true
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }

  belongs_to :room, foreign_key: 'room_id'
  has_many :students
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:uid]
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers'
  validates :name, presence: true
  validates :uid, presence: true,
                  uniqueness: { case_sensitive: true },
                  length: { minimum: 8, maximum: 16 },
                  format: { with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers' }

  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(['uid = :value', { value: uid }]).first
    else
      where(conditions).first
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_root, except: [:index, :new, :create]
  before_action :set_room, only: [:edit, :update, :show, :destroy]
  def index
    @user_rooms = UserRoom.where(user_id: current_user.id)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params_room)
    if @room.save
      UserRoom.create(room_id: @room.id, user_id: current_user.id)
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  def show
    @user_rooms = UserRoom.where(user_id: current_user.id)
  end

  def edit
    @user_rooms = UserRoom.where(room_id: params[:id])
  end

  def update
    if @room.update_attributes(params_room)
      redirect_to room_path
    else
      render 'edit'
    end
  end

  def destroy
    return unless @room.destroy

    redirect_to rooms_path
  end

  private

  def move_to_root
    @user_rooms = UserRoom.where(room_id: params[:id])
    return if @user_rooms.exists?(user_id: current_user.id)

    redirect_to root_path
  end

  def params_room
    params.require(:room).permit(:name)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_rooms_helper.rb
module UserRoomsHelper
end

app/views/groups/new.html.erb
<div class="form">
  <div class="form-title">
    <h2>グループ新規作成</h2>
  </div>
  <%= form_with model: @group, local: true do |f| %>
  <div class="form-errors">
  <%= render 'shared/error_messages', model: f.object %>
  </div>
  <div class="field">
    <div class="form-label">
    <%= f.label :name,"グループ名" %>
    </div>
    <div class="form-field">
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>
  </div>

  <div class="actions">
    <span>
    <%= f.submit "作成する" %>
    </span>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Wasurena</title>
    <meta name="勿忘" content="保育園、幼稚園送迎バス管理Webアプリケーション">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

      <%= yield %>
    <%= render partial:'shared/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div>
    <p>©️ 2022 rrr-ryu</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div id="header-container">
    <div id="logo">
      <%= link_to "勿 忘", root_path, class:"logo-main"%>
      <%= link_to "Wasurena", root_path, class:"logo-sub"%>
    </div>
    <div id="header-right">
      <ul id="header-lists">
      <% if user_signed_in?%>
        <li class="header-list">
        <%= link_to "グループ一覧", rooms_path %>
        </li>
        <li class="header-list">
        <%= link_to "グループ作成", new_room_path %>
        </li>
      <% else%>
        <li class="header-list">
        <%= link_to "新規登録", new_user_registration_path, class:"header-list-item"%>
        </li>
        <li class="header-list">
        <%= link_to "ログイン", new_user_session_path, class:"header-list-item"%>
        </li>
      <% end %>
      </ul>
      <div id="header-user">
        <% if user_signed_in?%>
        <div id="header-user-name">
        <p><%= current_user.name%><span>　▽</span></p>
        </div>
        <ul id="hidden">
        <li><%=link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
        <% end %>
      </div>

    </div>
  </div>
</header>

app/views/shared/_second_header.html.erb
<header>
  <div id="header-container">
    <div id="logo">
      <%= link_to "勿 忘", root_path, class:"logo-main"%>
      <%= link_to "Wasurena", root_path, class:"logo-sub"%>
    </div>
    <div id="header-right">
      <ul id="header-lists">
        <li class="header-list">
          <%= link_to "児童一覧", room_students_path(room_id: params[:room_id]) %></li>
        </li>
        <li class="header-list">
          <%= link_to "児童登録", new_room_student_path(room_id: params[:room_id]) %>
        </li>
        <li class="header-list">
          <%= link_to "クラス作成", new_room_team_path(room_id: params[:room_id]) %>
        </li>
        <li class="header-list">
          <%= link_to "送迎作成", new_room_pickup_path(room_id: params[:room_id]) %>
        </li>
      </ul>
      
      <div id="header-user">
        <% if user_signed_in?%>
          <div id="header-user-name">
          <p><%= current_user.name%><span>　▽</span></p>
          </div>
          <ul id="hidden">
            <li class="hidden-list"><%= link_to "全出席リセット", room_students_attend_reset_path, method: :put%></li>
            <li class="hidden-list"><%= link_to "全送迎リセット", room_students_ride_reset_path, method: :put%></li>
            <li class="hidden-list"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% end %>
      </div>

    </div>
  </div>
</header>

app/views/shared/_third_header.html.erb
<header>
  <div id="header-container">
    <div id="logo">
      <%= link_to "勿 忘", root_path, class:"logo-main"%>
      <%= link_to "Wasurena", root_path, class:"logo-sub"%>
    </div>
    <div id="header-right">
      <ul id="header-lists">
        <li class="header-list">
          <%= link_to "児童一覧", room_students_path(room_id: params[:room_id]) %></li>
      </ul>
      <div id="header-user">
        <% if user_signed_in?%>
        <div id="header-user-name">
        <p><%= current_user.name%><span>　▽</span></p>
        </div>
        <ul id="hidden">
        <li><%=link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
        <% end %>
      </div>

    </div>
  </div>
</header>